// <auto-generated />
namespace E16_ST3ITS3ExamOrdinary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CourseFKRemove : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CourseFKRemove));
        
        string IMigrationMetadata.Id
        {
            get { return "201612120854239_CourseFKRemove"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
